chore(config): support --edit options

diff --git a/commands/config b/commands/config
--- a/commands/config
+++ b/commands/config
@@ -3,6 +3,10 @@
 help() {
   echo "Usage:"
   echo "  zservice config <service_name> [options...]"
+  echo ""
+  echo "Options:"
+  echo "  --edit                Edit config file"
+  echo "  -h, --help            Print help"
 }
 
 core() {
@@ -13,6 +17,21 @@ core() {
   
   local service_name=$1
   local args=${@:2}
+  local edit=false
+  if [ -z "${service_name}" ]; then
+    log::error "service name is required"
+    exit 1
+  fi
+
+  if [ "${args}" = "--edit" ]; then
+    edit=true
+  fi
+
+  if [ "${edit}" = "true" ]; then
+    local config_path=$(service::get_config_path $service_name)
+    vim $config_path
+    exit 0
+  fi
 
   service::run $service_name config $args
 }
