fix(core): service:run not found app

diff --git a/core/fn b/core/fn
--- a/core/fn
+++ b/core/fn
@@ -99,6 +99,11 @@ service::list_sub_services() {
     log::error "[$(timestamp)][service] service($name) not found"
     exit 1
   fi
+
+  if [ ! -d "$service_path" ]; then
+    log::error "[$(timestamp)][service] service($name) not found"
+    exit 1
+  fi
   
   # @TODO
   service::load_config $name
@@ -118,6 +123,11 @@ service::run() {
   log::debug "[$(timestamp)][service] service command: $commands"
 
   if [ "$service_path" = "" ]; then
+    log::error "[$(timestamp)][service] service($name) not found"
+    exit 1
+  fi
+
+  if [ ! -d "$service_path" ]; then
     log::error "[$(timestamp)][service] service($name) not found"
     exit 1
   fi
@@ -255,12 +265,17 @@ service::load_mod() {
 service::load_config() {
   local name=$1
   if [ -z "$name" ]; then
-    log::error "[$(timestamp)][service::load_mod] name is required"
+    log::error "[$(timestamp)][service::load_config] name is required"
     exit 1
   fi
 
   # @TODO
   export SERVICE_DIR=$(service::get_path $name)
+  if [ ! -d "$SERVICE_DIR" ]; then
+    log::error "[$(timestamp)][service::load_config] service is not invalid"
+    exit 1
+  fi
+
   export SERVICE_DATA=$(service::get_data_path $name)
   export SERVICE_LOGS=$(service::get_logs_path $name)
   export SERVICE_CONFIGS=$(service::get_configs_path $name)
