chore(install): fix fetch

diff --git a/core/fn b/core/fn
--- a/core/fn
+++ b/core/fn
@@ -359,6 +359,13 @@ service::clone() {
     cd $service_path
     local current_tag=$(git describe --tags)
     if [ "$current_tag" != "$version" ]; then
+      git fetch origin $version >> $ZMICRO_LOG_UPDATE_PATH 2>>$ZMICRO_LOG_ERROR_PATH
+      if [ "$?" != "0" ]; then
+        echo "[$(timestamp)][service::clone] git fetch error ${name} ..."
+        tail -n 50 $ZMICRO_LOG_ERROR_PATH
+        exit -1
+      fi
+
       git checkout $version >> $ZMICRO_LOG_UPDATE_PATH 2>>$ZMICRO_LOG_ERROR_PATH
       if [ "$?" != "0" ]; then
         echo "[$(timestamp)][service::clone] git checkout error ${name} ..."
